UnnecessaryKeywords = {
    'a', 'an', 'the', 'and', 'or', 'in', 'on', 'at',
    'with', 'by', 'for', 'to', 'from', 'is', 'am', 'are', 'was', 'were',
    'have', 'has', 'had', 'do', 'does', 'did', 'you', 'me', 'my', 'I',
    'he', 'him', 'his', 'she', 'her', 'it', 'we', 'us', 'our', 'they', 'them', 'their',
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
    'some', 'any', 'all', 'each', 'every', 'much', 'many', 'few', 'little', 'some', 'several',
    'more', 'less', 'most', 'least', 'other', 'another', 'same', 'different', 'new', 'old',
    'former', 'latter', 'this', 'that', 'these', 'those', 'here', 'there', 'now', 'then',
    'today', 'yesterday', 'tomorrow', 'soon', 'later', 'nowadays', 'currently', 'previously',
    'recently', 'finally', 'initially', 'specifically', 'generally', 'basically', 'essentially',
    'really', 'truly', 'clearly', 'obviously', 'actually', 'literally', 'virtually', 'especially',
    'particularly', 'approximately', 'precisely', 'effectively', 'efficiently', 'immediately', 'directly',
    'accordingly', 'consequently', 'therefore', 'thus', 'however', 'nevertheless', 'nonetheless', 'moreover',
    'furthermore', 'additionally', 'besides', 'in addition', 'on the other hand', 'on the contrary', 'otherwise',
    'alternatively', 'similarly', 'likewise', 'comparatively', 'contrastingly', 'demonstrably', 'apparently',
    'supposedly', 'allegedly', 'notably', 'notwithstanding', 'regardless', 'indeed', 'undeniably', 'unquestionably',
    'conspicuously', 'prominently', 'significantly', 'substantially', 'considerably', 'remarkably', 'noteworthy',
    'unfortunately', 'fortunately', 'surprisingly', 'interestingly', 'curiously', 'fortunately', 'fortunately',
    'unfortunately', 'consequently', 'as a result', 'because', 'since', 'due to', 'owing to', 'thus', 'therefore',
    'for this reason', 'in summary', 'to conclude', 'to summarize', 'overall', 'in conclusion', 'finally', 'furthermore',
    'moreover', 'additionally', 'besides', 'in addition', 'on the other hand', 'on the contrary', 'otherwise', 'alternatively',
    'similarly', 'likewise', 'comparatively', 'contrastingly', 'demonstrably', 'apparently', 'supposedly', 'allegedly', 'notably',
    'notwithstanding', 'regardless', 'indeed', 'undeniably', 'unquestionably', 'conspicuously', 'prominently', 'significantly',
    'substantially', 'considerably', 'remarkably', 'noteworthy', 'unfortunately', 'fortunately', 'surprisingly', 'interestingly',
    'curiously', 'fortunately', 'fortunately', 'unfortunately', 'consequently', 'as a result', 'because', 'since', 'due to', 'owing to',
    'thus', 'therefore', 'for this reason', 'in summary', 'to conclude', 'to summarize', 'overall', 'in conclusion', 'finally', 'furthermore',
    'moreover', 'additionally', 'besides', 'in addition', 'on the other hand', 'on the contrary', 'otherwise', 'alternatively', 'similarly',
    'likewise', 'comparatively', 'contrastingly', 'demonstrably', 'apparently', 'supposedly', 'allegedly', 'notably', 'notwithstanding',
    'regardless', 'indeed', 'undeniably', 'unquestionably', 'conspicuously', 'prominently', 'significantly', 'substantially', 'considerably',
    'remarkably', 'noteworthy', 'unfortunately', 'fortunately', 'surprisingly', 'interestingly', 'curiously', 'fortunately', 'fortunately',
    'unfortunately', 'consequently', 'as a result', 'because', 'since', 'due to', 'owing to', 'thus', 'therefore', 'for this reason', 'in summary',
    'to conclude', 'to summarize', 'overall', 'in conclusion', 'finally', 'furthermore', 'moreover', 'additionally', 'besides', 'in addition',
    'on the other hand'}
