# Generated by Django 4.2.9 on 2024-01-17 06:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("mcq", "MCQ"), ("subjective", "Subjective")],
                        default="MCQ",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("correct_answer", models.TextField()),
                ("other_dependencies", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("questions", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("created", "Created"),
                            ("conducted", "Conducted"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("conduced_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_app.question",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_app.test",
                    ),
                ),
            ],
        ),
    ]
