# Generated by Django 4.2.9 on 2024-01-19 02:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("MCQ", "MCQ"), ("SUBJECTIVE", "SUBJECTIVE")],
                        default="MCQ",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("correct_answer", models.TextField()),
                ("other_dependencies", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("CREATED", "CREATED"),
                            ("CONDUCTED", "CONDUCTED"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("conduced_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestResponse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
