# Generated by Django 4.2.9 on 2024-01-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_to_candidates", to="user.candidate"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.employee",
            ),
        ),
        migrations.AddField(
            model_name="testresponse",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.candidate",
            ),
        ),
        migrations.RemoveField(model_name="test", name="questions",),
        migrations.AddField(
            model_name="test",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="tests", to="test_app.question"
            ),
        ),
    ]
