# Generated by Django 4.2.9 on 2024-01-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("CREATED", "CREATED"),
                    ("CONDUCTED", "CONDUCTED"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
