# Generated by Django 4.2.9 on 2024-01-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("test_app", "0002_test_assigned_to_test_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_to_candidates", to="user.employee"
            ),
        ),
    ]
