# Generated by Django 4.2.9 on 2024-01-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("test_app", "0003_alter_test_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("MCQ", "MCQ"), ("Subjective", "Subjective")],
                default="MCQ",
                max_length=10,
            ),
        ),
        migrations.RemoveField(model_name="test", name="assigned_to",),
        migrations.AlterField(
            model_name="test",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by",
                to="user.employee",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Created", "Created"),
                    ("Conducted", "Conducted"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_to",
                to="user.employee",
            ),
        ),
    ]
