# Generated by Django 4.2.9 on 2024-01-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        (
            "test_app",
            "0004_alter_question_question_type_remove_test_assigned_to_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_to",
                to="user.department",
            ),
        ),
    ]
